---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sniffit.fullname" . }}
  labels:
{{ include "sniffit.labels" . | indent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "sniffit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sniffit.fullname" . }}-grpc
  labels:
{{ include "sniffit.labels" . | indent 4 }}
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  ports:
    - name: grpc
      port: 9900
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "sniffit.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}