#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Service
metadata:
  name: #@ "{}-http".format(data.values.name)
  labels:
    app: #@ data.values.name
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: ClusterIP
  ports:
    - port: 9999
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: #@ data.values.name
---
apiVersion: v1
kind: Service
metadata:
  name: #@ "{}-grpc".format(data.values.name)
  labels:
    app: #@ data.values.name
  annotations:
    cloud.google.com/load-balancer-type: "Internal"
spec:
  type: LoadBalancer
#@ if data.values.service.grpc.address:
  loadBalancerIP: #@ data.values.service.grpc.address
#@ end
  externalTrafficPolicy: Local
  ports:
    - name: grpc
      port: 9900
      targetPort: grpc
      protocol: TCP
  selector:
    app: #@ data.values.name
